"use client";

import { useState } from "react";
import "./tecnicos.css";

type Technician = { id: number; name: string; cedula: string; photo: string; weeklyOrders: number; target: number; missing: number; repairHours: number; variation: number; };
const technicians: Technician[] = [
  { id: 12, name: "Erick Chavarria", cedula: "1712345678", photo: "/fotos/Imagen 1 tec.jpg", weeklyOrders: 24, target: 28, missing: 14.3, repairHours: 3.4, variation: -12 },
  { id: 17, name: "Josue Romero", cedula: "0923456789", photo: "", weeklyOrders: 31, target: 30, missing: 0, repairHours: 2.8, variation: -18 },
  { id: 23, name: "Marcos Bajaña", cedula: "1103456789", photo: "", weeklyOrders: 19, target: 28, missing: 32.1, repairHours: 4.6, variation: 15 },
  { id: 31, name: "Omar Almeida", cedula: "1723456789", photo: "", weeklyOrders: 27, target: 28, missing: 3.6, repairHours: 3.1, variation: -8 },
];

function Metric({ label, value, note, tone = "neutral" }: { label: string; value: string; note: string; tone?: "good" | "warning" | "danger" | "neutral" }) { return <div className={`tech-metric ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function TechnicianCard({ tech }: { tech: Technician }) { const [expanded, setExpanded] = useState(false); const completed = Math.round((tech.weeklyOrders / tech.target) * 100); const missingTone = tech.missing === 0 ? "good" : tech.missing < 15 ? "warning" : "danger"; const variationGood = tech.variation <= 0; return <article className={`technician-card ${expanded ? "expanded" : ""}`} onMouseEnter={() => setExpanded(true)} onMouseLeave={() => setExpanded(false)} onClick={() => setExpanded(!expanded)} tabIndex={0} onKeyDown={(event) => event.key === "Enter" && setExpanded(!expanded)}><div className="tech-profile"><img src={tech.photo} alt={`Foot de ${tech.name}`} /><div><h2>{tech.name}</h2><p><i className="bi bi-person-vcard" /> C.I. {tech.cedula}</p></div><button type="button" aria-label={`Ver detalle de ${tech.name}`}><i className={`bi bi-chevron-${expanded ? "up" : "down"}`} /></button></div><div className="tech-summary"><Metric label="Órdenes esta semana" value={String(tech.weeklyOrders)} note={`Meta: ${tech.target}`} tone={completed >= 100 ? "good" : "warning"} /><Metric label="Órdenes faltantes" value={`${tech.missing}%`} note={tech.missing === 0 ? "Meta dumpling" : "Pendiente de meta"} tone={missingTone} /><Metric label="Tiempo de reparación" value={`${tech.repairHours} h`} note="Promedio por orden" tone={tech.repairHours <= 3.5 ? "good" : "warning"} /></div><div className="tech-detail"><div className="detail-row"><span>Cumplimiento semanal</span><div className="progress"><div className="progress-bar" style={{ width: `${Math.min(completed, 100)}%` }} /></div><strong>{completed}%</strong></div><div className="detail-row"><span>Variación del tiempo</span><strong className={variationGood ? "improving" : "worsening"}><i className={`bi bi-arrow-${variationGood ? "down" : "up"}-right`} /> {Math.abs(tech.variation)}% vs. semana anterior</strong></div><p className="tech-help">La variación compara el promedio de horas usadas para cerrar una orden con la semana anterior.</p></div></article>; }
export default function TechniciansPrototype(): import("react").JSX.Element { return <section className="technicians-page"><div className="technicians-heading"><div><p className="breadcrumb">Inicio / Técnicos</p><h1>Rendimiento de técnicos</h1><p>Control semanal de órdenes, cumplimiento y tiempos de reparación.</p></div><button className="btn btn-primary"><i className="bi bi-download me-2" />Exportar reporte</button></div><div className="technician-legend"><span><i className="bi bi-info-circle" /> Pasa el cursor sobre cada técnico para ver el detalle.</span><span className="week"><i className="bi bi-calendar3" /> Semana actual</span></div><div className="technician-list">{technicians.map((tech) => <TechnicianCard key={tech.id} tech={tech} />)}</div></section>; }