"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import "./ticket-detail.css";

export function TicketPreviewDetail({ id }: { id: string }) {
  const [messages, setMessages] = useState<string[]>([]); const [text, setText] = useState(""); const [status, setStatus] = useState("Abierto");
  function send(event: FormEvent) { event.preventDefault(); if (text.trim()) { setMessages((current) => [...current, text.trim()]); setText(""); } }
  return <section className="td-wrap"><Link href="/tickets/mis-tickets" style={{ color: "#64748b", fontSize: 13 }}><i className="bi bi-arrow-left" /> Volver a Mis Solicitudes</Link><header className="td-head" style={{ marginTop: 12 }}><div><span>SYS-{id.padStart(6, "0")}</span><h2>Solicitud de soporte y requerimiento de sistemas</h2><p>Portal de Requerimientos · Sistemas TI</p></div><b>{status}</b></header><div className="td-grid"><article><h3><i className="bi bi-card-text" /> Solicitud</h3><p>Detalle del requerimiento registrado desde el Portal de Requerimientos y Soporte.</p><dl><div><dt>Empresa origen</dt><dd>NOVICOMPU</dd></div><div><dt>Tienda</dt><dd>Tienda asignada</dd></div><div><dt>Contacto</dt><dd>—</dd></div><div><dt>Ticket MBA</dt><dd>—</dd></div></dl></article><article><h3><i className="bi bi-chat-left-text" /> Conversación</h3>{messages.length ? <ul className="td-history">{messages.map((message, index) => <li key={index}><p>{message}</p><time>Ahora</time></li>)}</ul> : <p className="td-empty">Sin mensajes.</p>}<form className="td-reply" onSubmit={send}><textarea value={text} onChange={(event) => setText(event.target.value)} rows={3} placeholder="Escribe una respuesta..." /><button>Enviar mensaje</button></form></article><article><h3><i className="bi bi-arrow-repeat" /> Gestión</h3><form className="td-reply" onSubmit={(event) => event.preventDefault()}><select value={status} onChange={(event) => setStatus(event.target.value)}><option>Abierto</option><option>En proceso</option><option>En espera</option><option>Resuelto</option><option>Cerrado</option></select><textarea rows={2} placeholder="Razón del cambio" /><button>Cambiar estado</button></form></article><article><h3><i className="bi bi-paperclip" /> Adjuntos</h3><p className="td-empty">Sin adjuntos.</p><form className="td-reply" onSubmit={(event) => event.preventDefault()}><input type="file" /><button>Subir archivo</button></form></article></div></section>;
}
