"use client";
import { FormEvent, useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api";

type Branch = { id: string; code: string; name: string };
export function TicketCreate() {
  const [branches, setBranches] = useState<Branch[]>([]); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void api<Branch[]>("/api/branches").then(setBranches).catch(() => setError("No se pudieron cargar las sucursales.")); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); setError(""); setSuccess(""); try { const ticket = await api<{ code: string }>("/api/tickets", { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ serviceBranchId: form.get("branch"), type: form.get("type"), category: form.get("category"), priority: form.get("priority"), originCompany: form.get("company"), storeName: form.get("store") || null, contactPhone: form.get("phone") || null, title: form.get("title"), description: form.get("description") }) }); event.currentTarget.reset(); setSuccess(`Ticket ${ticket.code} creado correctamente.`); } catch (e) { setError(e instanceof ApiError ? e.message : "No fue posible crear el ticket."); } finally { setSaving(false); } }
  return <form className="panel entry-form" onSubmit={submit}><h2>Crear nuevo ticket</h2><p>La solicitud se guarda directamente en SGN nuevo.</p><div className="field-grid"><label>Sucursal de atención<select name="branch" required defaultValue=""><option value="" disabled>Seleccione una sucursal</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.code} — {branch.name}</option>)}</select></label><label>Tipo<select name="type" required defaultValue=""><option value="" disabled>Seleccione</option><option value="SoporteTecnico">Soporte técnico</option><option value="Sistemas">Sistemas TI</option></select></label><label>Categoría<input name="category" required placeholder="Ej.: Hardware, red, sistema" /></label><label>Prioridad<select name="priority" required defaultValue="Normal"><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label><label>Empresa origen<input name="company" required placeholder="Empresa o área solicitante" /></label><label>Teléfono de contacto<input name="phone" placeholder="Opcional" /></label><label className="wide">Tienda / ubicación<input name="store" placeholder="Opcional" /></label><label className="wide">Título<input name="title" required placeholder="Resume el requerimiento" /></label><label className="wide">Descripción<textarea name="description" required rows={5} placeholder="Describe el problema, impacto y evidencia disponible." /></label></div>{error && <p className="form-error">{error}</p>}{success && <p style={{ color: "#166534", marginTop: 14 }}>{success}</p>}<div className="actions"><button type="reset" className="secondary">Limpiar</button><button className="primary" disabled={saving}>{saving ? "Creando…" : "Crear ticket"}</button></div></form>;
}
